services:
  bank_simulator:
    container_name: bank_simulator
    image: bbyars/mountebank:2.8.1
    ports:
      - "2525:2525"
      - "8080:8080"
    command: --configfile /imposters/bank_simulator.ejs
    volumes:
      - type: bind
        source: ./imposters
        target: /imposters
  payment_service:
    container_name: payment_service
    build: .
    command: ./main
    ports:
      - "8090:8090"